insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Aston Reservoir');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Belmont Moat');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Belmont Pool');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Bradeley Hall Pool');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Bridgewater Canal');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Catch Penny Pool');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Farm Pool');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Founders Pool');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Friars Pool');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Golden Pond');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Grimsditch Mill Pool');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Llangollen Canal');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Lymmvale Stock Pond');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Lymmvale');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Micklewrights Flash');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Nunsmere');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Oak Pool');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Oasis Pool');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Peover Eye');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'River Dane, Daisybank Farm');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'River Severn, Abermule');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'River Severn, Atcham Above Tern');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'River Severn, Atcham Below Tern');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'River Severn, Atcham Wroxeter');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'River Severn, Llandrinio');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'River Severn, Rossall');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'River Tern');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'River Vyrnwy, Llandrinio');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'River Vyrnwy, Melynoig Fawr');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Rowan Pool');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Serpentine Pool');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Shakerley Mere');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Shropshire Union Canal');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Spring, New and Top Pools');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Tabley Mere');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Tabley Moat');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Village Pool');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Whitley Pool');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Whitley Pool 2');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Willow Pool');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Woodside Pool');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Wrinehill Pool');
insert into lookup(lookup_type, lookup_value) values ('FISHERY', 'Yew Tree Pool');
