insert into lookup(lookup_type, lookup_value) values ('SPECIES', 'BLANK');
insert into lookup(lookup_type, lookup_value) values ('SPECIES', 'Barbel');
insert into lookup(lookup_type, lookup_value) values ('SPECIES', 'Bleak');
insert into lookup(lookup_type, lookup_value) values ('SPECIES', 'Carp (Common)');
insert into lookup(lookup_type, lookup_value) values ('SPECIES', 'Carp (Mirror)');
insert into lookup(lookup_type, lookup_value) values ('SPECIES', 'Carp (Leather)');
insert into lookup(lookup_type, lookup_value) values ('SPECIES', 'Carp (Ghost)');
insert into lookup(lookup_type, lookup_value) values ('SPECIES', 'Crucian Carp');
insert into lookup(lookup_type, lookup_value) values ('SPECIES', 'Chub');
insert into lookup(lookup_type, lookup_value) values ('SPECIES', 'Dace');
insert into lookup(lookup_type, lookup_value) values ('SPECIES', 'Eel');
insert into lookup(lookup_type, lookup_value) values ('SPECIES', 'Perch');
insert into lookup(lookup_type, lookup_value) values ('SPECIES', 'Pike');
insert into lookup(lookup_type, lookup_value) values ('SPECIES', 'Roach');
insert into lookup(lookup_type, lookup_value) values ('SPECIES', 'Rudd');
insert into lookup(lookup_type, lookup_value) values ('SPECIES', 'Bream (Bronze)');
insert into lookup(lookup_type, lookup_value) values ('SPECIES', 'Bream (Silver)');
insert into lookup(lookup_type, lookup_value) values ('SPECIES', 'Tench');
commit;