version: 2
jobs:
  build:
    working_directory: ~/johnhunsley/returns

    parallelism: 1

    shell: /bin/bash --login

#    environment:
#          CIRCLE_ARTIFACTS: target/circleci-artifacts
#          CIRCLE_TEST_REPORTS: target/circleci-test-results

    docker:
      - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
        command: /sbin/init

    steps:
      - checkout

#      - run: echo $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS

      - run: pwd

      - run: ls -l .circleci/

#      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS

      - restore_cache:
          key: returns-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: returns-{{ checksum "pom.xml" }}

      - run: mvn integration-test

      - store_test_results:
          path: ~/johnhunsley/returns/target/surefire-reports/


#      - run: mkdir -p $CIRCLE_TEST_REPORTS/junit/
#
#      - run: find . -type f -regex ".*/$CIRCLE_TEST_REPORTS/surefire-reports/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;

      - run: mvn clean package

      - store_artifacts:
          path: ~/johnhunsley/returns/target/*.jar


  deploy:
    machine:
        enabled: true
    working_directory: ~/johnhunsley/returns/target
    environment:
      # todo different envs for different branches / tags
      - HEROKU_APP: lymm-returns-api-dev
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-assets-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Setup Heroku
          command: bash ./../.circleci/setup-heroku.sh
      - run:
          command: |
            git push heroku returns:master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build